### ISSUE TITLE
negative temperatures

### ISSUE THREAD

**Issue by BerndSchr** [prof2004/Distribution#1]
I use org.openhab.binding.ws980wifi-3.3.0-SNAPSHOT.jar. Today the temperatures goes below 0. I got 6553.5. 
I make a rule and calculate (65535-65536)/10. Can you make a new jar file. Thank you!

**Comment by prof2004** [comment]
Hi Bernd,
the binding ws980wifi is not supported anymore. It has become part of binding org.openhab.binding.fineoffsetweatherstation. Please use this binding.

**Comment by prof2004** [comment]
the binding ws980wifi is not supported anymore. It has become part of binding org.openhab.binding.fineoffsetweatherstation. Please use this binding.
